# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: Dugonzal <dugonzal@student.42urduliz.com>  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/09/24 18:21:25 by Dugonzal          #+#    #+#              #
#    Updated: 2024/09/24 18:32:13 by Dugonzal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM redis:7.4-alpine3.20

#COPY redis.conf /usr/local/etc/redis/redis.conf

CMD redis-server
