name: ft_transcendence

services:
  proxy:
    container_name: proxy
    build:
      context: ./proxy/
      dockerfile: Dockerfile
    networks:
      - frontend
    env_file:
      - proxy/.env_proxy
    restart: always
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
      - app
    ports:
      - "80:80"

  app:
    container_name: app
    build:
      context: ./app/
      dockerfile: Dockerfile
    networks:
      - frontend
      - backend
    env_file:
      - app/.env_app
    restart: always
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
      - db

  db:
    container_name: db
    build:
      context: ./db/
      dockerfile: Dockerfile
    networks:
      - backend
    env_file:
      - db/.env_db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # Volume ensures data persists
    volumes:
      - db-data:/var/lib/postgresql/data

  vue:
    container_name: vue
    build:
      context: ./vue/
      dockerfile: Dockerfile
    networks:
      - frontend
    restart: always
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  media_volume:
  static_volume:
  db-data:
