name: ft_transcendence

services:
  proxy:
    container_name: proxy
    build:
      context: ./docker/proxy/
      dockerfile: Dockerfile
    networks:
      - frontend
    env_file:
      - docker/proxy/.env_proxy
    restart: always
    depends_on:
      - app
    ports:
      - "8080:8080"

  app:
    container_name: app
    build:
      context: ./docker/app/
      dockerfile: Dockerfile
    networks:
      - frontend
      - backend
    env_file:
      - docker/app/.env_app
    expose:
      - "8000"
    restart: always
    depends_on:
      - db

  db:
    container_name: db
    build:
      context: ./docker/db/
      dockerfile: Dockerfile
    networks:
      - backend
    env_file:
      - docker/db/.env_db
    expose:
      - "8000"
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # Volume ensures data persists
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db-data:
