# docker-compose-backend.yml

name: ft_transcendence_backend

services:
  keys:
    container_name: keys
    build:
      context: ../backend/keys
      dockerfile: Dockerfile
    env_file: ../backend/.env-django
    environment:
      - PRIVATE_KEY_PATH=/usr/src/app/secrets/jwt_auth_private.pem
      - PUBLIC_KEY_PATH=/usr/src/app/secrets/jwt_auth_public.pem
    restart: always
    volumes:
      - shared_models:/usr/src/app/shared_models
      - jwt_auth_keys:/usr/src/app/secrets
    networks:
      - backend

  api:
    container_name: api
    build:
      context: ../backend/api
      dockerfile: Dockerfile
    env_file: ../backend/.env-django
    restart: always
    volumes:
      - shared_models:/app/shared_models
    networks:
      - backend
      - frontend
    depends_on:
      - keys
      - admin

  admin:
    container_name: admin
    build:
      context: ../backend/admin
      dockerfile: Dockerfile
    env_file: ../backend/.env-django
    restart: always
    volumes:
      - shared_models:/usr/src/app/shared_models
    networks:
      - frontend
      - backend
    depends_on:
      - keys

  pong:
    container_name: pong
    build:
      context: ../backend/pong
      dockerfile: Dockerfile
    env_file: ../backend/.env-django
    restart: always
    volumes:
      - shared_models:/usr/src/app/shared_models
    networks:
      - frontend
      - backend
    depends_on:
      - keys

  database:
    container_name: db
    build:
      context: ../database/
      dockerfile: Dockerfile
    networks:
      - backend
      - metrics
    env_file: ../database/.env-postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    shm_size: 128mb

networks:
  frontend:
    external: true
  backend:
    driver: bridge
  metrics:
    external: true

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../volumes/backend/db
  jwt_auth_keys:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../volumes/backend/jwt_auth_keys
  shared_models:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/shared_models
