# docker-compose.yml

name: ft_transcendence

services:
  reverse-proxy:
    container_name: proxy
    build:
      context: ../reverse-proxy/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - frontend
    depends_on:
      - vue

  vue:
    container_name: vue
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    networks:
    - frontend
    restart: always
    volumes:
      - frontend_static:/vue-project/src/

networks:
  frontend:
    external: true

volumes:
  frontend_static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../frontend/vue-project/src/