name: ft_transcendence

services:
  reverse-proxy:
    container_name: proxy
    build: ../reverse-proxy/
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    networks:
      - traefik

  frontend:
    container_name: frontend
    build: ../frontend/
    networks:
      - traefik
    volumes:
      - node_modules:/frontend/node_modules
      - frontend:/frontend
    restart: always
    depends_on:
      - reverse-proxy
<<<<<<< HEAD
      - database
  redis:
    container_name: redis
    build: ../backend/redis/
    env_file: ../.env.dev
    restart: always
    #volumes:
    #  - redis:/redis
    networks:
      - ft_transcendence
    ports:
      - 6379

  #secrets:
  #  auth_traefik:
=======

#secrets:
#  auth_traefik:
>>>>>>> merge

networks:
  traefik:
    name: traefik
    driver: bridge
volumes:
  frontend:
    driver: local
    driver_opts:
      type: none
      o: bind
<<<<<<< HEAD
      device: ../frontend/frontend/
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../database/db
  redis:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/redis/redis
=======
      device: ../frontend/frontend
  node_modules:
>>>>>>> merge
