name: ft_transcendence

services:
  proxy:
    container_name: proxy
    build: ../proxy/
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - proxy:/proxy
    networks:
      - proxy

  frontend:
    container_name: frontend
    build: ../frontend/
    networks:
      - proxy
    volumes:
      - node_modules:/frontend/node_modules
      - frontend:/frontend
    restart: always
    depends_on:
      - proxy
  redis:
    container_name: redis
    build: ../backend/redis/
    restart: always
    volumes:
      - redis:/redis
    networks:
      - proxy
    ports:
      - 6379
#secrets:
#  auth_traefik:

networks:
  proxy:
    name: proxy
    driver: bridge
volumes:
  proxy:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../proxy/
  frontend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../frontend/frontend
  redis:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/redis/
  node_modules:
