name: ft_transcendence

services:
  reverse-proxy:
    container_name: proxy
    build: ../reverse-proxy/
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    networks:
      - frontend

<<<<<<< Updated upstream
  database:
    container_name: db
    build: ../database/
    env_file: ../database/.env-postgres
    ports:
      - 5432
    # volumes:
      # - db-data:/var/lib/postgresql/data
    restart: always
    shm_size: 128mb
    networks:
      - ft_transcendence
=======
>>>>>>> Stashed changes
  frontend:
    container_name: frontend
    build: ../frontend/
    networks:
      - frontend
    volumes:
      - node_modules:/frontend/node_modules
      - frontend:/frontend
      - node_modules:/frontend/node_modules
    restart: always
    depends_on:
      - reverse-proxy

<<<<<<< Updated upstream
  authentication:
    container_name: autentication
    build: ../backend/authentication/
    env_file: ../backend/.env-django
    restart: always
    volumes:
      - authentication:/authentication
    networks:
      - ft_transcendence
    depends_on:
      - reverse-proxy
      - database
=======
>>>>>>> Stashed changes
#secrets:
#  auth_traefik:

networks:
  frontend:
    external: true

volumes:
  frontend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../frontend/frontend
  node_modules:
