name: ft_transcendence_backend

services:
  pong:
    container_name: pong
    build: ../backend/pong
    env_file: ../.env.dev
    restart: always
    volumes:
      - pong:/pong
    networks:
      - ft_transcendence
    depends_on:
      - authentication

  authentication:
    container_name: autentication
    build: ../backend/authentication/
    env_file: ../.env.dev
    restart: always
    volumes:
      - authentication:/authentication
    networks:
      - ft_transcendence

  friendship:
    container_name: friendship
    build: ../backend/friendship/
    env_file: ../.env.dev
    restart: always
    volumes:
      - friendship:/friendship
    networks:
      - ft_transcendence
    depends_on:
      - authentication

  livechat:
    container_name: livechat
    build: ../backend/livechat/
    env_file: ../.env.dev
    restart: always
    volumes:
      - livechat:/livechat
    networks:
      - ft_transcendence
    depends_on:
      - authentication

networks:
  ft_transcendence:
    external: true

volumes:
  pong:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/pong/pong/
  authentication:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/authentication/authentication/
  friendship:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/friendship/friendship/
  livechat:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/livechat/livechat
