name: ft_transcendence  

services:
  proxy:
    container_name: reverse_proxy
    build: ../proxy/
    networks:
      - ft_trancendence   
    env_file:
      - ../proxy/.env_proxy
    restart: always
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"

  app:
    container_name: app
    build: ../backend/app/
    networks:
    - ft_trancendence 
    env_file:
    - ../backend/app/.env_app
    restart: always
    volumes:
    - static_volume:/home/app/web/static
    - media_volume:/home/app/web/media
    depends_on:
    - database

  database:
    container_name: database
    build: ../Database/
    networks:
    - ft_trancendence 
    env_file:
      - ../Database/.env_db
    restart: always
    shm_size: 128mb
    volumes:
      - db-data:/var/lib/postgresql/data

  vue:
    container_name: vue
    build: ../frontend/vue/
    networks:
    - ft_trancendence
    restart: always
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media

networks:
  ft_trancendence:
    name: ft_trancendence
    driver: bridge

volumes:
  media_volume:
  static_volume:
  db-data:
