name: ft_transcendence_backend

services:
  db:
    container_name: db
    build: ../database/
    env_file: ../backend/.env-django
    ports:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    shm_size: 128mb
    networks:
      - backend

  migrations:
    container_name: migrations
    build: ../backend/migrations/
    env_file: ../backend/.env-django
    networks:
      - backend
    depends_on:
      - db
    volumes:
      - auth:/auth
      - pong:/pong
      - friendship:/friendship

  keys:
    container_name: keys
    build: ../backend/keys/
    env_file: ../backend/.env-django
    restart: always
    volumes:
      - jwt_auth_keys:/keys
    networks:
      - backend
    depends_on:
      - db
      - migrations

  auth:
    container_name: auth
    build: ../backend/auth/
    env_file: ../backend/.env-django
    restart: always
    volumes:
      - auth:/auth
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - keys

  pong:
    container_name: pong
    build: ../backend/pong
    env_file: ../backend/.env-django
    restart: always
    volumes:
      - pong:/pong
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - keys
      - auth

  friendship:
    container_name: friendship
    build: ../backend/friendship/
    env_file: ../backend/.env-django
    restart: always
    volumes:
      - friendship:/friendship
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - keys
      - auth
      - pong

networks:
  frontend:
    external: true
  backend:
    name: ft_transcendence-backend
    driver: bridge

volumes:
  jwt_auth_keys:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/keys/keys
  pong:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/pong/pong/
  auth:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/auth/auth/
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../database/db
  friendship:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/friendship/friendship/
