name: ft_transcendence

services:
  proxy:
    container_name: reverse_proxy
    build: ../proxy/
    networks:
      - frontend
    env_file:
      - ../proxy/.env_proxy
    restart: always
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"

  app:
    container_name: app
    build: ../backend/app/
    networks:
      - frontend
      - backend
    env_file:
      - ../backend/app/.env_app
    restart: always
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
      - db

  db:
    container_name: db
    build: ../db/
    networks:
      - backend
    env_file:
      - ../db/.env_db
    restart: always
    shm_size: 128mb
    volumes:
      - db-data:/var/lib/postgresql/data

  vue:
    container_name: vue
    build: ../frontend/vue/
    networks:
    - frontend
    restart: always
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  media_volume:
  static_volume:
  db-data:
