name: ft_transcendence_backend

services:
  keys:
    container_name: keys
    build: ../backend/keys
    env_file: ../backend/.env-django
    restart: always
    volumes:
      - jwt_auth_keys:/keys
    networks:
      - ft_transcendence

  api:
    container_name: api
    build: ../backend/api
    env_file: ../backend/.env-django
    restart: always
    #volumes:
    # - shared_models:/app/shared_models
    networks:
      - ft_transcendence
    depends_on:
      - keys
      - admin

  admin:
    container_name: admin
    build: ../backend/admin # si el context y el file son lo mismo, mejor asi???
    env_file: ../backend/.env-django
    restart: always
    #volumes:
    # - shared_models:/usr/src/app/shared_models
    networks:
      - ft_transcendence
    depends_on:
      - keys

  pong:
    container_name: pong
    build: ../backend/pong
    env_file: ../backend/.env-django
    restart: always
    #volumes:
    # - shared_models:/usr/src/app/shared_models
    networks:
      - ft_transcendence
    depends_on:
      - keys

networks:
  ft_transcendence:
    external: true

volumes:
  jwt_auth_keys:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/keys/
  #  shared_models:
  # driver: local
  #driver_opts:
  # type: none
  #o: bind
  #device: ../backend/shared_models
