name: ft_transcendence

services:
  reverse-proxy:
    container_name: proxy
    build: ../reverse-proxy/
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    networks:
      - frontend

  frontend:
    container_name: frontend
    build: ../frontend/
    networks:
      - frontend
    volumes:
      - node_modules:/frontend/node_modules
      - frontend:/frontend
    restart: always
    depends_on:
      - reverse-proxy

#secrets:
#  auth_traefik:

networks:
  frontend:
    external: true

volumes:
  frontend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../frontend/frontend
  node_modules:
