# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose-frontend.yml                        :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: Dugonzal <dugonzal@student.42urduliz.com>  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/07/14 22:28:10 by Dugonzal          #+#    #+#              #
#    Updated: 2024/07/16 21:46:23 by Dugonzal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

name: ft_transcendence

services:
  login:
    container_name: login
    build: ../frontend/login/
    networks:
      - ft_trancendence
    restart: always
    #volumes:
    #  - static_volume:/home/app/web/static
    #  - media_volume:/home/app/web/media
