name: ft_transcendence_metrics

services:
  prometheus:
    container_name: prometheus
    build: ../monitoring/prometheus
    restart: always
    networks:
      - metrics

  grafana:
    container_name: grafana
    build: ../monitoring/grafana
    restart: always
    networks:
      - metrics

networks:
  metrics:
    external: true

volumes:
  prometheus-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../monitoring/prometheus/
  grafana-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../monitoring/grafana/
