name: ft_transcendence_backend

services:
  db:
    container_name: db
    build: ../database/
    env_file: ../backend/.env-django
    ports:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    shm_size: 128mb
    networks:
      - backend

  auth:
    container_name: auth
    build: ../backend/auth/
    env_file: ../backend/.env-django
    restart: always
    volumes:
      - auth:/auth
      - dependencies:/opt/venv/
    networks:
      - frontend
      - backend
    depends_on:
      - db

  migration:
    container_name: migration
    build: ../backend/migration/
    env_file: ../backend/.env-django
    restart: always
    volumes:
      - auth:/usr/src/app/auth
      - pong:/usr/src/app/pong
      - friendship:/usr/src/app/friendship
      - dependencies:/opt/venv/
    networks:
      - backend
    depends_on:
      - db
      - auth

  pong:
    container_name: pong
    build: ../backend/pong
    env_file: ../backend/.env-dev
    restart: always
    volumes:
      - pong:/pong
      - dependencies:/opt/venv/
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - auth
      - migration

  friendship:
    container_name: friendship
    build: ../backend/friendship/
    env_file: ../backend/.env-django
    restart: always
    volumes:
      - friendship:/friendship
      - dependencies:/opt/venv/
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - auth
      - pong
      - migration

networks:
  frontend:
    external: true
  backend:
    name: ft_transcendence-backend
    driver: bridge

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../volumes/db
  dependencies:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../volumes/dependencies
  pong:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/pong/pong/
  auth:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/auth/auth/
  friendship:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/friendship/friendship/
