name: ft_transcendence

services:
  reverse-proxy:
    container_name: proxy
    build: ../reverse-proxy/
    restart: always
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - ft_transcendence

  frontend:
    container_name: frontend
    image: frontend:0.0.1
    build: ../frontend/
    networks:
      - ft_transcendence
    restart: always
    volumes:
      - vue_volume:/home/app/web/static/
      - vue_volume:/home/app/web/media/
    depends_on:
      - reverse-proxy

networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge

volumes:
  vue_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../volumes/frontend/
