name: ft_transcendence_backend

services:
  keys:
    container_name: keys
    build: ../backend/keys
    restart: always
    volumes:
      - keys:/keys
    networks:
      - ft_transcendence
    ports:
      - 8000

  pong:
    container_name: pong
    build: ../backend/pong
    env_file: ../.env.dev
    restart: always
    volumes:
      - pong:/pong
    networks:
      - ft_transcendence
    depends_on:
      - keys

  authentication:
    container_name: autentication
    build: ../backend/authentication/
    env_file: ../.env.dev
    restart: always
    volumes:
      - authentication:/authentication
    networks:
      - ft_transcendence
    depends_on:
      - keys

  friendship:
    container_name: friendship
    build: ../backend/friendship/
    env_file: ../.env.dev
    restart: always
    volumes:
      - friendship:/friendship
    networks:
      - ft_transcendence
    depends_on:
      - keys

networks:
  ft_transcendence:
    external: true

volumes:
  keys:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/keys/keys/
  pong:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/pong/pong/
  authentication:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/authentication/authentication/
  friendship:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/friendship/friendship/
