name: ft_transcendence_backend

services:
  db:
    container_name: db
    build: ../database/
    env_file: ../database/.env-postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    shm_size: 128mb
    networks:
      - backend

  keys:
    container_name: keys
    build: ../backend/keys/
    env_file: ../backend/.env-dev
    restart: always
    volumes:
      - jwt_auth_keys:/keys
    networks:
      - backend
    depends_on:
      - db

  auth:
    container_name: auth
    build: ../backend/auth/
    env_file: ../backend/.env-dev
    restart: always
    volumes:
      - auth:/auth
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - keys

  pong:
    container_name: pong
    build: ../backend/pong
    env_file: ../backend/.env-dev
    restart: always
    volumes:
      - pong:/pong
    networks:
      - backend
    depends_on:
      - db
      - keys

  admin:
    container_name: admin
    build: ../backend/admin/
    env_file: ../backend/.env-dev
    restart: always
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - auth
      - keys

networks:
  frontend:
    external: true
  backend:
    name: ft_transcendence-backend
    driver: bridge

volumes:
  jwt_auth_keys:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/keys/keys
  pong:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/pong/pong
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../database/db
  auth:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/auth/auth/
