# Generated by Django 5.0.7 on 2024-10-02 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one', models.CharField(max_length=255)),
                ('player_two', models.CharField(max_length=255)),
                ('winner', models.CharField(max_length=255)),
                ('loser', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('position', models.IntegerField(blank=True)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('total_games', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SemiFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semi_one', models.CharField(max_length=255)),
                ('semi_two', models.CharField(max_length=255)),
                ('semi_three', models.CharField(max_length=255)),
                ('semi_four', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PongGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_type', models.CharField(choices=[('AI', 'AI Tournament'), ('2P', '2P Tournament')], default='2P', max_length=2)),
                ('winner', models.CharField(max_length=255)),
                ('name_player1', models.CharField(blank=True, max_length=255, null=True)),
                ('name_player2', models.CharField(blank=True, max_length=255, null=True)),
                ('score_player1', models.IntegerField()),
                ('score_player2', models.IntegerField()),
                ('id_player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player1_data', to='pong.player')),
                ('id_player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player2_data', to='pong.player')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament8P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_type', models.CharField(default='8P', max_length=3)),
                ('final_round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pong.finalround')),
                ('players', models.ManyToManyField(to='pong.player')),
                ('semi_finals', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pong.semifinal')),
            ],
        ),
    ]
