# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: Dugonzal <dugonzal@student.42urduliz.com>  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/26 16:56:16 by Dugonzal          #+#    #+#              #
#    Updated: 2024/06/28 15:47:47 by Dugonzal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:
  # Login 
  Login:
    build: ../Frontend/Login
    image: login-${Tag}
    networks:
    - ft_trancendence
    restart: always
    volumes:
      - Login:/Login/
  # backend
  authentication:
    build: ../Backend/Authentication/
    image: authentication-${Tag}
    networks:
    - ft_trancendence
    volumes:
      - autentication:/authentication/
    restart: always
    env_file:
    - ../.env.dev
    depends_on:
      database:
        condition: service_healthy
    develop:
      watch:
      - action: rebuild 
        path: /autentication
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  autentication:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../Backend/Authentication/authentication
  # frontend 
  Login:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../Frontend/Login/Login
