# Generated by Django 5.1.1 on 2024-09-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
