# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    traefik.toml                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: Dugonzal <dugonzal@student.42urduliz.com>  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/11 13:40:30 by Dugonzal          #+#    #+#              #
#    Updated: 2024/06/29 10:04:16 by Dugonzal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

[global]
checkNewVersion = true
sendAnonymousUsage = true

[entryPoints]
[entryPoints.web]
address = ":80"
[entryPoints.web.http]
[entryPoints.web.http.redirections]
[entryPoints.web.http.redirections.entryPoint]
to = "websecure"
scheme = "https"

[entryPoints.websecure]
address = ":443"
#[entryPoints.tcp]
#address = ":3306"
#  [entryPoints.udp]
#address = ":8081/udp"


[api]
dashboard = true
insecure = true

[http.middlewares]
[http.middlewares.auth.basicAuth]
users = [
  "ciclo:ciclo", # Reemplaza con tu usuario y contraseña generados
]


[Log]
level = "DEBUG"

[accessLog]
filePath = "/etc/traefik/access.log"
bufferingSize = 100

[metrics]
[metrics.prometheus]
entryPoint = "traefik"
addEntryPointsLabels = true
addServicesLabels = true
buckets = [0.1, 0.3, 1.2, 5.0]

[providers]
[providers.docker]
endpoint = "unix:///var/run/docker.sock"
exposedByDefault = false

[http.routers.api]
rule = "Host(`localhost`)"
entryPoints = ["web"]
middlewares = ["auth"]
service = "api@internal"
